version: '3.8'

services:
  # Spring Boot Backend with Neon PostgreSQL
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dsa-tracker-backend
    environment:
      - SPRING_PROFILES_ACTIVE=neon
    ports:
      - "8080:8080"
    networks:
      - dsa-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dsa-tracker-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dsa-tracker-network

networks:
  dsa-tracker-network:
    driver: bridge